In [1]:
from keras.models import Model
from keras.layers import Dense, Input
from keras.losses import categorical_crossentropy
from keras.optimizers import adam
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import numpy as np
from keras.preprocessing.image import load_img
from sklearn.preprocessing import OneHotEncoder

Using TensorFlow backend.


In [2]:
mnist = np.load("../datasets/mnist_train_small.npy")

In [3]:
X, y = mnist[:, 1:], mnist[:, 0]

In [4]:
ohe = OneHotEncoder(categories="auto")

In [5]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
y_hot = ohe.fit_transform(y.reshape(-1, 1))

In [7]:
y.shape

(19999,)

In [8]:
in_layer = Input((784,))
d1 = Dense(400, activation="tanh")(in_layer)
d2 = Dense(200, activation="tanh")(d1)
d3 = Dense(50, activation="tanh")(d2)
out = Dense(10, activation="softmax")(d3)

In [9]:
model = Model(inputs=[in_layer], outputs=[out])

In [10]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 400)               314000    
_________________________________________________________________
dense_2 (Dense)              (None, 200)               80200     
_________________________________________________________________
dense_3 (Dense)              (None, 50)                10050     
_________________________________________________________________
dense_4 (Dense)              (None, 10)                510       
Total params: 404,760
Trainable params: 404,760
Non-trainable params: 0
_________________________________________________________________


In [11]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y_hot, test_size=0.33, random_state=42)

In [12]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [13]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
13399/13399 [==============================] - 5s 366us/step - loss: 0.5842 - accuracy: 0.8242
Epoch 2/10
13399/13399 [==============================] - 4s 295us/step - loss: 0.4329 - accuracy: 0.8625
Epoch 3/10
13399/13399 [==============================] - 4s 293us/step - loss: 0.4266 - accuracy: 0.8654
Epoch 4/10
13399/13399 [==============================] - 4s 284us/step - loss: 0.4137 - accuracy: 0.8680
Epoch 5/10
13399/13399 [==============================] - 4s 297us/step - loss: 0.3712 - accuracy: 0.8777
Epoch 6/10
13399/13399 [==============================] - 4s 300us/step - loss: 0.3507 - accuracy: 0.8891
Epoch 7/10
13399/13399 [==============================] - 4s 288us/step - loss: 0.3427 - accuracy: 0.8925
Epoch 8/10
13399/13399 [==============================] - 4s 291us/step - loss: 0.3541 - accuracy: 0.8861
Epoch 9/10
13399/13399 [==============================] - 4s 290us/step - loss: 0.3387 - accuracy: 0.8939
Epoch 10/10
13399/13399 [=====================

In [14]:
model.evaluate(X_test, y_test)

6600/6600 [==============================] - 1s 83us/step


[0.3713211933410529, 0.8807575702667236]

In [15]:
len(X_test)

6600

In [16]:
model.predict(X_test[:10])

array([[2.6077594e-04, 2.6120294e-02, 3.0957636e-01, 3.3756623e-01,
        1.7456218e-04, 6.9117700e-03, 1.4036736e-05, 1.6426900e-01,
        1.4847536e-01, 6.6316044e-03],
       [1.5130256e-04, 1.7804818e-05, 2.3802404e-05, 3.5996042e-04,
        4.0820029e-04, 1.7390089e-04, 7.3684492e-07, 9.7877216e-01,
        1.1594123e-04, 1.9976102e-02],
       [1.7907061e-01, 2.5308146e-03, 4.9993330e-01, 7.8136832e-02,
        2.4943228e-04, 5.8371476e-03, 6.2201649e-04, 5.5412997e-02,
        1.2761076e-01, 5.0596107e-02],
       [7.0287366e-05, 5.1305917e-05, 8.3354671e-06, 6.9733374e-03,
        1.2582287e-02, 1.0073536e-02, 3.3137123e-05, 1.7519519e-03,
        2.4108437e-03, 9.6604508e-01],
       [1.3811431e-04, 2.4078253e-03, 1.9681091e-05, 2.3356758e-03,
        5.8405042e-01, 4.6526622e-03, 6.7597773e-04, 1.9110559e-02,
        2.8137023e-02, 3.5847199e-01],
       [1.3027898e-04, 1.2783275e-04, 1.9777008e-06, 5.1624386e-04,
        3.1013443e-04, 9.9649835e-01, 9.2029717e-05, 2.23

In [17]:
y_test[:10].todense().argmax(axis=1)

matrix([[7],
        [7],
        [0],
        [9],
        [4],
        [5],
        [4],
        [6],
        [9],
        [2]])

In [18]:
img = load_img("../datasets/nums/eight.jpeg", target_size=(28, 28), grayscale=True)
type(img)
plane = (np.array(img) < 100).astype(int) * 255
plt.imshow(plane, cmap="gray")
model.predict(np.array([plane.flatten()])).argsort(axis=1)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras_preprocessing/image/utils.py:104: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '


ImportError: Could not import PIL.Image. The use of `load_img` requires PIL.